# Generated by Django 4.2.5 on 2023-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "admin_table ",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE(R)", "CSE(Regular)"),
                            ("CSE(H)", "CSE(Honors)"),
                            ("CSIT", "CS&IT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "academicyear",
                    models.CharField(
                        choices=[("2023-24", "2023-24"), ("2022-23", "2022-23")],
                        max_length=10,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("ODD", "ODD"), ("EVEN", "EVEN")], max_length=10
                    ),
                ),
                ("Year", models.IntegerField()),
                ("coursecode", models.CharField(max_length=20)),
                ("coursetitle", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "course_table",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("facultyid", models.BigIntegerField(unique=True)),
                ("Fullname", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("others", "others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE(R)", "CSE(Regular)"),
                            ("CSE(H)", "CSE(Honors)"),
                            ("CSIT", "CS&IT"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[("MTECH", "MTECH"), ("PH.D", "PH.D")], max_length=50
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("prof", "Professor"),
                            ("Assoc.prof", "Associate professor"),
                            ("Asst.prof", "Assitant professor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("password", models.CharField(default="klu123", max_length=100)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "faculty_table",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("studentid", models.BigIntegerField(unique=True)),
                ("Fullname", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("others", "others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE(R)", "CSE(Regular)"),
                            ("CSE(H)", "CSE(Honors)"),
                            ("CSIT", "CS&IT"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[("BTECH", "BTECH"), ("MTECH", "MTECH")], max_length=50
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("ODD", "ODD"), ("EVEN", "EVEN")], max_length=10
                    ),
                ),
                ("Year", models.IntegerField()),
                ("password", models.CharField(default="klu123", max_length=100)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "student_table",
            },
        ),
    ]
