# Generated by Django 4.2.5 on 2023-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0005_rename_facultycoursemapping_facultycoursemappings"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="facultycoursemapping",
            table="facutlycoursemapp_table",
        ),
    ]
