# Generated by Django 4.2.5 on 2023-09-18 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0007_fcoursemappings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacultyCourseMapping",
        ),
    ]
