# Generated by Django 4.2.5 on 2023-09-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0008_delete_facultycoursemappings"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Ltps",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="academicyear",
            field=models.CharField(
                choices=[("2023-24", "2023-24"), ("2022-23", "2022-23")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="designation",
            field=models.CharField(
                choices=[
                    ("prof", "Professor"),
                    ("Assoc.prof", "Associate professor"),
                    ("Asst.prof", "Assitant professor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("others", "others")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="qualification",
            field=models.CharField(
                choices=[("MTECH", "MTECH"), ("PH.D", "PH.D")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("others", "others")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.CharField(
                choices=[("BTECH", "BTECH"), ("MTECH", "MTECH")], max_length=50
            ),
        ),
        migrations.CreateModel(
            name="FacultyCourseMappings",
            fields=[
                ("mappingsid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "facutlycoursemapping_table",
            },
        ),
    ]
