# Generated by Django 4.2.5 on 2023-09-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0010_delete_facultycoursemappings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyCourseMappings",
            fields=[
                ("mappingsid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "facutlycoursemapping_table",
            },
        ),
    ]
