# Generated by Django 4.2.5 on 2023-09-25 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0011_facultycoursemappings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacultyCourseMappings",
        ),
    ]
