# Generated by Django 4.2.5 on 2023-09-29 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0012_delete_facultycoursemappings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Ltps",
            new_name="ltps",
        ),
    ]
