# Generated by Django 4.2.5 on 2023-09-29 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0013_rename_ltps_course_ltps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="ltps",
        ),
    ]
