# Generated by Django 4.2.5 on 2023-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0014_remove_course_ltps"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ltps",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
