# Generated by Django 4.2.5 on 2023-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0015_course_ltps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="ltps",
        ),
        migrations.AddField(
            model_name="course",
            name="coursecredits",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="ltps_struct",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
