# Generated by Django 4.2.6 on 2023-10-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_course_credits_remove_course_ltps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursecredits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ltps_struct',
        ),
    ]
