# Generated by Django 4.2.6 on 2023-10-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_remove_course_coursecredits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcoursemappings',
            name='Facultyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fcoursemappings_facultyid', to='adminapp.faculty'),
            preserve_default=False,
        ),
    ]
