# Generated by Django 4.2.6 on 2023-10-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_fcoursemappings_facultyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcoursemappings',
            name='Facultyid',
        ),
    ]
