# Generated by Django 4.2.6 on 2023-10-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_fcoursemappings_facultyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcoursemappings',
            old_name='mapid',
            new_name='id',
        ),
    ]
