# Generated by Django 4.2.6 on 2023-11-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_rename_mapid_fcoursemappings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentcoursemapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=10)),
                ('year', models.IntegerField(max_length=10)),
                ('semester', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'studentcoursemapping_table',
            },
        ),
    ]
