# Generated by Django 4.2.6 on 2023-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_studentcoursemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursemapping',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
